# Generated by Django 5.2.6 on 2025-11-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField(verbose_name='材料')),
                ('instructions', models.TextField(verbose_name='作り方')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
