# Generated by Django 5.2.6 on 2025-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('和食', '和食'), ('洋食', '洋食'), ('スイーツ', 'スイーツ')], default='和食', max_length=10),
        ),
    ]
